title: Product
pages: false
files: true

status:
  draft: true
  listed: true
  unlisted: true

columns:          
  main:
    width: 1/2
    sections:
      content:
        type: fields

        fields:
          type:
            width: 1/3
            label: Product Type
            type: select
            options: query
            query: page.parent.products.split
            required: true
          price:
            width: 1/3
            label: Price
            type: number
            step: .01
            before: $
            min: 0
            required: true
          availability:
            width: 1/3
            label: Availability
            type: toggle
            default: true
            text: 
              - "Sold Out"
              - "In Stock"
          width:
            width: 1/2
            label: Width
            type: number
            required: true
          height:
            width: 1/2
            label: Height
            type: number
            required: true
          highlights:
            label: Unique Product Highlights
            type: structure
            fields:
              highlight:
                label: Highlight
                type: text
          description:
            label: Description
            type: textarea
            size: small
            required: true
  sidebar:
    width: 1/2
    sections:
      Gallery:
        type: files
        required: true
        min: 1
        layout: cards
        size: tiny
        image:
          ratio: 1/1